/**
 * Created by mc7995 on 6/22/17.
 */
db = connect("localhost:27017/cosmoforms");

/* pets demo */
db.pets.insert({ "id_field" : 2343242323, "nombre" : "Cosmo", "age" : 8, "active" : true, "favorite_foods" : [ "purina one", "water", "blue buffalo biscuits", "deli meats", "wood", "rubber" ], "exercise_schedule" : [ { "day" : "monday", "start_time" : "6:00", "end_time" : "7:30", "active_day" : true }, { "day" : "thursday", "start_time" : "16:00", "end_time" : "18:00", "active_day" : false } ], "res_address" : { "street" : "123 main st", "city" : "los angeles", "state" : "wa", "zip" : 90023 }, "biz_address" : { "street" : "987 center ct", "city" : "san fransico", "state" : "ca", "zip" : 91123 }, "allergies" : [ "peanuts", "chocolate", "milk" ], "moar_allergies" : [ "peanuts", "chocolate", "milk" ] });
db.pets.insert({ "favorite_foods" : [ "dry food", "carrots", "bbq chips", "taco bell tacos" ], "res_address" : { "zip" : 90234, "city" : "san diego", "street" : "123 center court", "state" : "ca" }, "active" : true, "nombre" : "Milo", "exercise_schedule" : [ { "start_time" : "16:00", "end_time" : "18:00", "active_day" : true, "day" : "monday" }, { "start_time" : "12:00", "end_time" : "14:00", "active_day" : true, "day" : "wednesday" } ], "age" : 12, "coat" : "short", "friendly" : true, "shakes" : "yes" });
db.pets.insert({ "nombre" : "Zara", "age" : 1 });
db.pets.insert({ "nombre" : "Otis", "age" : 2, "snacks" : [ "water", "tacos" ] });
db.pets.insert({ "nombre" : "Eddie", "age" : 12 });

/* sources demo */
db.sources.insert({"name":"GOOG","active":true,"messagesPerMinute":300,"collectionName":"capped_goog_ips","isProxy":false,"isETL":true,"ipPoolSize":25,"retryCount":3,"connectionTimeout":30000,"readTimeout":30000,"requestTimeout":30000,"httpHeaders":[{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","Accept-encoding":"gzip, deflate, sdch","Accept-language":"en-US,en;q=0.8,es;q=0.6","User-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36","Connection":"keep-alive"},{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","Accept-encoding":"gzip, deflate, sdch","Accept-language":"en-US,en;q=0.8,es;q=0.6","User-agent":"Mozilla/5.0 (MSIE 10.0; Windows NT 6.1; Trident/5.0)","Connection":""},{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","Accept-encoding":"gzip, deflate, sdch","Accept-language":"en-US,en;q=0.8,es;q=0.6","User-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20120101 Firefox/33.0","Connection":"keep-alive"},{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","Accept-encoding":"gzip, deflate","Accept-language":"en-us","User-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4","Connection":"keep-alive"},{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","Accept-encoding":"gzip, deflate, sdch","Accept-language":"en-US,en;q=0.8,es;q=0.6","User-agent":"Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14","Connection":"keep-alive"}],"scanUrl":[{"domain":"maps.google.com","mipIdRegex":"cid=([^&]+)"},{"domain":"maps.googleapis.com","mipIdRegex":"placeid=([^&]+)"}],"scanner":{"scanRate":{"messagesPerMinute":300,"liveMessagesPerMinute":300,"batchMessagesPerMinute":260,"bulkMessagesPerMinute":260},"rate_to_scan":{"RR_messagesPerMinute":300,"RR_liveMessagesPerMinute":300,"RR_batchMessagesPerMinute":260,"RR_bulkMessagesPerMinute":260}},"provider":"argo","apps":["argo","presence","presence_old","mdm","argo360ui"],"topic":"GOOG","isReview":true});

/* source_configs demo */
db.source_configs.insert({"source":"YELP","enabled":true,"endpoints":[{"endpointType":"SEARCH","endpointId":"yelp search","sourceType":"API","authParams":{"consumer_key":"2fbytNBBLaVbSXxMBBTnCA","consumer_secret":"v2D3UEAzvSZbFtUCehkP5qSRJhw","token":"ihr-yGFXn7yqzjbNjV6mCxyyBPW7HcQS","token_secret":"7mrXeBi_2TFtTFuYVyErjZHId2A","sign_method":"HMAC-SHA1"},"validScanTypes":["search","catgeo"],"url":"http://api.yelp.com/v2/search?term=<q>&location=<city>+<st>","responseFormatType":"JSON","staticParams":{"limit":"5"},"appendParams":[],"requiredAppendParams":[],"swapParams":["q","city","st"],"requiredSwapParams":["q","city","st"],"rotatableParams":{},"requiredRotatableParams":[],"staticHttpHeaders":{},"mipExtractor":"default","resultsLimit":"3"},{"endpointType":"SEARCH","endpointId":"yelp phone search","sourceType":"API","authParams":{"consumer_key":"2fbytNBBLaVbSXxMBBTnCA","consumer_secret":"v2D3UEAzvSZbFtUCehkP5qSRJhw","token":"ihr-yGFXn7yqzjbNjV6mCxyyBPW7HcQS","token_secret":"7mrXeBi_2TFtTFuYVyErjZHId2A","sign_method":"HMAC-SHA1"},"validScanTypes":["search","phone"],"inclusion":false,"url":"https://api.yelp.com/v2/phone_search/?phone=<phone>","responseFormatType":"JSON","staticParams":{"limit":"5"},"appendParams":[],"requiredAppendParams":[],"swapParams":["phone"],"requiredSwapParams":["phone"],"rotatableParams":{},"requiredRotatableParams":[],"staticHttpHeaders":{},"mipExtractor":"default","resultsLimit":"1"},{"endpointType":"MIP","endpointId":"yelp mip","sourceType":"API","authParams":{"consumer_key":"2fbytNBBLaVbSXxMBBTnCA","consumer_secret":"v2D3UEAzvSZbFtUCehkP5qSRJhw","token":"ihr-yGFXn7yqzjbNjV6mCxyyBPW7HcQS","token_secret":"7mrXeBi_2TFtTFuYVyErjZHId2A","sign_method":"HMAC-SHA1"},"url":"http://api.yelp.com/v2/business/<mip>","responseFormatType":"JSON","staticParams":{},"appendParams":[],"requiredAppendParams":[],"swapParams":["mip"],"requiredSwapParams":["mip"],"rotatableParams":{},"requiredRotatableParams":[],"staticHttpHeaders":{},"mipExtractor":""},{"endpointType":"REVIEWS","endpointId":"yelp reviews","sourceType":"HTML","authParams":{},"url":"http://www.yelp.com/biz/<mip>","responseFormatType":"HTML","staticParams":{},"appendParams":[],"requiredAppendParams":[],"swapParams":["mip"],"requiredSwapParams":["mip"],"rotatableParams":{},"requiredRotatableParams":[],"staticHttpHeaders":{},"mipExtractor":""}]});
